services:
  nav2-demo:
    build:
      context: .
      dockerfile: Dockerfile
    image: cla-nav2:latest
    container_name: nav2-demo
  
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - TURTLEBOT3_MODEL=waffle
      - TB1_PARAMS=/ros2_ws/src/params/nav2_tb1.yaml
      - TB2_PARAMS=/ros2_ws/src/params/nav2_tb2.yaml
      - DEFAULT_MAP=/ros2_ws/src/maps/my_map.yaml
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./src/maps:/ros2_ws/src/maps
      - ./src/params:/ros2_ws/src/params
    tty: true
    stdin_open: true