# /root/data/nav2_tb2.yaml
amcl:
  ros__parameters:
    use_sim_time: true
    base_frame_id: tb2/base_link
    odom_frame_id: tb2/odom
    global_frame_id: tb2/map
    scan_topic: tb2/scan
map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: /root/data/my_map.yaml
bt_navigator:
  ros__parameters: { use_sim_time: true }
controller_server:
  ros__parameters:
    use_sim_time: true
    FollowPath.error_derivative_scale: 1.0
local_costmap:
  ros__parameters:
    use_sim_time: true
    global_frame: tb2/odom
    robot_base_frame: tb2/base_link
global_costmap:
  ros__parameters:
    use_sim_time: true
    global_frame: tb2/map
    robot_base_frame: tb2/base_link
planner_server:
  ros__parameters: { use_sim_time: true }
smoother_server:
  ros__parameters: { use_sim_time: true }
behavior_server:
  ros__parameters: { use_sim_time: true }
waypoint_follower:
  ros__parameters: { use_sim_time: true }
