amcl:
  ros__parameters:
    use_sim_time: true
    base_frame_id: tb1/base_link
    odom_frame_id: tb1/odom
    global_frame_id: tb1/map
    scan_topic: tb1/scan

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: /ros2_ws/src/maps/my_map.yaml
    frame_id: tb1/map

local_costmap:
  ros__parameters:
    global_frame: tb1/odom
    robot_base_frame: tb1/base_link

global_costmap:
  ros__parameters:
    global_frame: tb1/map
    robot_base_frame: tb1/base_link
